module.exports = {
  purge: {
    enabled: process.env.HUGO_ENVIRONMENT === 'production',
    content: ['./layouts/**/*.html', './assets/js/**/*.js'],
    options: {
      safelist: [
        'header--active',
        'nav--active',
        'menu-icon--active',
        'overlay--active',
        'btn-up--active',
        'pagination__button',
        'event',
        'event__item',
        'event__container-left',
        'event__municipio-departamento',
        'event__titulo',
        'event__nombre',
        'event__image-titulo',
        'event__container-right',
        'event__image',
        'slider-prev',
        'slider-next',
        'swiper-button-disabled',
        'single-navigation__item--active',
        'sub-menu-2--active',
        'modal',
        'modal--active',
        'modal__overlay',
        'modal__overlay--active',
        'modal__button-close',
        'modal--events',
        'modal--multimedia',
        'opacity-40',
        'swiper-pagination-bullet',
        'swiper-pagination-bullet-active',
        'publicaciones',
        'publicaciones__item',
        'publicaciones__tema',
        'publicaciones__nombre-publicacion',
        'publicaciones__descripcion',
        'publicaciones__fecha',
        'publicaciones__download',
        'publicaciones__text-right',
        'publicaciones--mt-4',
        'publicaciones--mt-2',
        'publicaciones---mt-8',
        'multimedia__button-galeria',
        'px-3',
        'w-full',
        'relative',
        'italic',
        'text-space-cadet',
        'mySwiper',
        'swiper-slide',
        'swiper-slide-thumb-active',
        'pt-12',
        'pb-6',
        'mx-auto',
        'galeria__child-1',
        'galeria__child-2',
        'galeria__title',
        'galeria__description',
        'galeria__comunidad-focalizada',
        'multimedia__item',
        'multimedia__button-play',
        'multimedia__type',
        'multimedia__details',
        'multimedia__title',
        'multimedia__description',
        'multimedia__lugar-comunidad',
        'multimedia__button-galeria',
        'multimedia__image',
        'multimedia__item',
        'sub-menu-icon--active',
        'sub-menu-2--active',
        'event__modal-panel',
        'event__modal--flex-justify',
        'event__modal-left',
        'event__modal-right',
        'event__modal--space-y-5',
        'event__modal--space-y-2',
        'event__modal--flex-center',
        'event__modal--space-x-2',
        'event__modal--space-x-3',
        'event__modal-paragraph',
        'event__modal-flex-responsive',
        'event__modal-title',
        'event__modal-italic',
        'event__modal--text-purple',
        'event__button',
        'swiper__image--thumbs',
        'swiper__image--multimedia',
        'swiperThumbs--events',
        'swiper-slide-thumb-active',
        'swiper-slide',
        'swiper-button-prev-events',
        'swiper-button-next-events',
        'video',
        'video__left',
        'video__right',
        'video--space-y-8',
        'video--flex',
        'video--items-center',
        'video--space-x',
        'video--text-purple',
        'video--italic',
        'video--justify-between',
        'video--font-size-22',
        'video--font-bold',
        'video-w-full',
        'video--custom-button',
        'col-start-1',
        'col-end-3',
        'invisible',
        'visible',
        'hidden',
        'swiper-slide--thumbs',
      ],
    },
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      fontSize: {
        xxxs: '0.5rem',
        xxs: '0.625rem',
      },
      backgroundImage: {
        'banner-home': 'url(/images/home/banner-home.png)',
        'banner-home-2': 'url(/images/home/banner-home-2.png)',
        'banner-home-3': 'url(/images/home/banner-home-3.png)',
        'banner-territorios': 'url(/images/territorios/banner-territorios.svg)',
        'banner-noticias': 'url(/images/noticias/banner-noticias.svg)',
        'banner-eventos': 'url(/images/eventos/banner-eventos.svg)',
        'banner-programa': 'url(/images/sobre-programa/banner-sobre-el-programa.svg)',
        'newsletter': 'url(/images/home/newsletter.png)',
        'banner-galeria': 'url(/images/galeria/banner-galeria.svg)',
        'banner-eventos-significativos': 'url(/images/eventos-significativos.svg)',
        'banner-inclusion-diversidad-genero': 'url(/images/inclusion-diversidad-genero.svg)',
      },
      colors: {
        'black': '#1A1A1A',
        'purple': '#5F2161',
        'cultured': '#fafafa',
        'space-cadet': '#3A3C6A',
        'rose': '#C5296A',
        'fern-green': '#4F7435',
        'magenta': '#963B62',
        'white-2': '#F0F0F2',
        'blue': '#3A3D81',
        'orange': '#D27028',
        'white-3': '#F8F8F9',
        'purple-opacity': 'rgb(126, 62, 107)',
        'thulian-pink': '#D7729C',
        'dark-moss-green': '#38601E',
        'olivine': '#B0C58F',
        'cambridge-blue': '#9EB290',
        'puce': '#B97D97',
        'platinum': '#E6E6E6',
        'tea-green': '#C3D3A9',
        'seasalt': '#F7F8F9',
      },
      screens: {
        'sm': '640px',
        // => @media (min-width: 640px) { ... }

        'md': '768px',
        // => @media (min-width: 768px) { ... }

        'lg': '1024px',
        // => @media (min-width: 1024px) { ... }

        'xl': '1366px',
        // => @media (min-width: 1366px) { ... }

        '2xl': '1536px',
        // => @media (min-width: 1536px) { ... }
      },
    },
  },
  variants: {
    extend: {
      borderWidth: ['last'],
      backgroundOpacity: ['checked'],
      backgroundColor: ['checked'],
    },
  },
  plugins: [
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/forms'),
  ],
};
