CREATE TABLE IF NOT EXISTS comunidades (
	id SERIAL PRIMARY KEY,
	municipio TEXT,
	region TEXT,
	departamento TEXT,
	nombre_comunidad TEXT,
	descripcion TEXT,
	num_personas INTEGER,
	num_familias INTEGER,
	min_distancia_casco_urbano INTEGER,
	km_distancia_casco_urbano INTEGER,
	vias_acceso TEXT,
	infraestructura_comunitaria TEXT,
	notas_infraestructura_comunitaria TEXT,
	infraestructura_salud_atencion_psicosocial TEXT,
	notas_infraestructura_salud_atencion_psicosocial TEXT,
	liderazgo_comunidad TEXT,
	inclusion_diversidad_genero TEXT,
	conectividad TEXT,
	comentarios_conectividad TEXT,
	punto_sole TEXT,
	comentarios_punto_sole TEXT,
	ppales_actividades_economicas_vocacion_productiva TEXT,
	comentarios_ppales_actividades_economicas_vocacion_productiva TEXT,
	comunidad_sostenible_uso_suelo TEXT,
	iniciativas_productivas_priorizadas TEXT,
	riesgo TEXT,
	otros_programas_usaid TEXT,
	alianzas_colaboradores TEXT,
	actividades_ocio TEXT,
	num_visitas_realizadas INTEGER,
	num_diagnosticos_rurales_participativos_realizados INTEGER,
	num_visitas_predio INTEGER,
	medios_comunicacion_narrativas_locales TEXT,
	org_con_proyeccion TEXT,
	org_focalizada TEXT,
	iniciativas_retomar_fortalecer_innovar TEXT,
	servicios_publicos_comunidades_focalizadas TEXT,
	comunidades_focalizadas_educacion_infraestructura_educativa TEXT,
	comunidades_focalizadas_practicas_organizativas TEXT,
	posibilidad_iniciativas_conjuntas_aliados_2 TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fichas_municipio (
	id SERIAL PRIMARY KEY,
	municipio TEXT,
	departamento TEXT,
	descripcion TEXT,
	region TEXT,
	comunidad_focalizada TEXT,
	centros_poblados_corregimiento TEXT,
	distribucion_poblacional_hombres INTEGER,
	distribucion_poblacional_mujeres INTEGER,
	poblacion_rural INTEGER,
	poblacion_urbana INTEGER,
	poblacion_discapacidad INTEGER,
	comunidades_etnicas_zona TEXT,
	asentamientos_indigenas INTEGER,
	resguardos_indigenas INTEGER,
	consejos_comunitarios INTEGER,
	total_poblacion_victima INTEGER,
	hombres_victimas_conflicto INTEGER,
	intersexuales_victimas_conflicto INTEGER,
	lgbt_victimas_conflicto INTEGER,
	mujeres_victimas_conflicto INTEGER,
	no_informa_victimas_conflicto INTEGER,
	num_sujetos_reparacion_colectiva INTEGER,
	num_planes_retorno_reubicacion_colectiva INTEGER,
	territorio_entidades_snariv_sivjrnr TEXT,
	priorizacion_convivencia_social_salud_mental TEXT,
	priorizacion_sexualidad_derechos_sexuales_reproductivos TEXT,
	priorizacion_gestion_diferencial_poblaciones_vulnerables TEXT,
	priorizacion_fortalecimiento_autoridad_sanitaria TEXT,
	eventos_salud_publica_predominantes TEXT,
	rips_salud_mental_poblacion_general TEXT,
	servicios_telemedicina_mpio_depto TEXT,
	total_pobreza_multidimensional TEXT,
	pobreza_multidimensional_urbano TEXT,
	pobreza_multidimensional_centro_poblado_rural_disperso TEXT,
	ppal_vocacion_mpio TEXT,
	observaciones_ppal_vocacion_mpio TEXT,
	ppal_uso_suelo TEXT,
	observaciones_ppal_uso_suelo TEXT,
	ppales_actividades_economicas TEXT,
	observaciones_ppales_actividades_economicas TEXT,
	trabajo_informal TEXT,
	espacios_socio_comunitarios TEXT,
	medios_comunicacion TEXT,
	iniciativas_org_sociedad_civil TEXT,
	programas_usaid TEXT,
	galeria TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eventos (
	id SERIAL PRIMARY KEY,
	nombre_evento TEXT,
	mes TEXT,
	dia_inicio TEXT,
	dia_finalizacion TEXT,
	comunidad TEXT,
	municipio TEXT,
	macroregion TEXT,
	tipo_agenda TEXT,
	descripcion TEXT,
	tipo_evento TEXT,
	abierto_cerrado TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eventos_municipios (
	id SERIAL PRIMARY KEY,
	municipio TEXT,
	departamento TEXT,
	nombre_evento TEXT,
	mes TEXT,
	tipo_evento TEXT,
	fecha_inicio TEXT,
	fecha_finalizacion TEXT
);

