name: Update reports
on:
  schedule:
    - cron: 10 */24 * * *

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install deps
        run: npm install
      - name: Generate reports
        run: npm run gen:reports
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "Update reports [gh-action]"
          git push